# Generated by Django 3.0.2 on 2020-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('user_type', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
