# Generated by Django 3.0.2 on 2020-02-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20200213_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'users_account'},
        ),
        migrations.AlterModelOptions(
            name='mcq_question',
            options={'verbose_name_plural': 'user_mcq_question'},
        ),
        migrations.RenameField(
            model_name='mcq_question',
            old_name='carrect_and',
            new_name='carrect_ans',
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='ans_is_carrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin.MCQ_Question', verbose_name='user_mcq_question'),
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin.Account', verbose_name='users_account'),
        ),
    ]
