# Generated by Django 3.0.2 on 2020-02-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20200217_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'user_mcq_options',
            },
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='Q',
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='ans_is_carrect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin.MCQ_Options', verbose_name='user_mcq_options'),
        ),
    ]
