# Generated by Django 3.0.2 on 2020-02-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20200218_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ans',
            name='ans_is_carrect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin.MCQ_Options'),
        ),
    ]
