# Generated by Django 3.0.2 on 2020-03-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20200219_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam_Time_Control',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mcq_options',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mcq_question',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='ans_is_carrect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.MCQ_Options'),
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_ans',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
